version: '3'
services:
  crypto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fl1pper-zer0
    ports:
      - 7001:4869
    restart: unless-stopped
    mem_limit: 1000M
    cpus: 1