version: '3'
services:
  crypto:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: number_js
    ports:
      - 7011:5000
    restart: unless-stopped
    mem_limit: 1000M
    cpus: 1
