services:
  postgres:
    image: postgres:16
    container_name: secrets_postgres
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass
      POSTGRES_DB: ctfdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: secrets_web
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=ctfuser
      - DB_PASS=ctfpass
      - DB_NAME=ctfdb


