version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: secrets_postgres
    environment:
      POSTGRES_USER: ctfuser
      POSTGRES_PASSWORD: ctfpass789654123597aaa
      POSTGRES_DB: ctfdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    mem_limit: 500M
    cpus: 1


  app:
    build: .
    container_name: secrets_web
    depends_on:
      - postgres
    ports:
      - "8000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ctfuser
      DB_PASS: ctfpass789654123597aaa
      DB_NAME: ctfdb
    restart: unless-stopped
    mem_limit: 1G
    cpus: 1

