version: "3.8"

services:
  spell_manager:
    build: .
    ports:
      - "1305:9090"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
    read_only: true
    cap_drop:
      - all
    privileged: true
    
