version: "3.8"

services:
  ctf:
    build: .
    ports:
      - "1337:1339"
    restart: unless-stopped
    mem_limit: 1000M
    cpus: 1
    read_only: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
      - "label=type:container_runtime_t"
      - "label=disable"
