version: '3'
services:
  crypto:
    build:
      context: ./src
      dockerfile: Dockerfile
    container_name: fl1pper-zer0
    ports:
      - 6000:4869
    restart: unless-stopped
    mem_limit: 2000M
    cpus: 2
